### PR TITLE
Release

### PR DESCRIPTION
**Pull request by avoinea**

### CODE REVIEW

**Comment by avoinea** [comment]
@dobri1408 Can you please check why cypress is red?

**Comment by dobri1408** [comment]
Hi @avoinea, I fixed the tests.

**Comment by dobri1408** [comment]
@avoinea  please see https://github.com/eea/volto-eea-website-theme/pull/149

**Review by avoinea — COMMENTED** [review]
@dobri1408 Please add missing dependency to file widget to be able to upload or select a subtitle file when using with a clean volto project and also add cypress for it.

Also, please cleanup the console warning:

```
Warning: Each child in a list should have a unique "key" prop.                                                                                                                                             
                                                                                                                                                                                                           
Check the top-level render call using <video>. See https://reactjs.org/link/warning-keys for more information.                                                                                             
    at NextCloudEmbed (/opt/sandbox/clean-volto-project/build/server.js:112208:3)                                                                                                                          
    at div                                                                                                                                                                                                 
    at Body (/opt/sandbox/clean-volto-project/build/server.js:111581:3)                                                                                                                                    
    at div                                                                                                                                                                                                 
    at View (/opt/sandbox/clean-volto-project/build/server.js:112038:5)                                                                                                                                    
    at /opt/sandbox/clean-volto-project/build/server.js:98603:5                                                                                                                                            
    at StyleWrapper (/opt/sandbox/clean-volto-project/build/server.js:23274:5)                                                                                                                             
    at RenderBlocks (/opt/sandbox/clean-volto-project/build/server.js:90837:5)                                                                                                                             
    at injectIntl(RenderBlocks)                                                                                                                                                                            
    at div                                                                                                                                                                                                 
    at Container (/opt/sandbox/clean-volto-project/node_modules/semantic-ui-react/dist/commonjs/elements/Container/Container.js:22:24)                                                                     
    at DefaultView (/opt/sandbox/clean-volto-project/build/server.js:89760:5)                                                                                                                              
    at injectIntl(DefaultView)                                                                                                                                                                             
    at div                                                                                                                                                                                                 
    at View (/opt/sandbox/clean-volto-project/build/server.js:91458:5)                                                                                                                                     
    at ConnectFunction (/opt/sandbox/clean-volto-project/node_modules/react-redux/lib/components/connectAdvanced.js:233:41)                                                                                
    at ConnectFunction (/opt/sandbox/clean-volto-project/node_modules/react-redux/lib/components/connectAdvanced.js:233:41)                                                                                
    at injectIntl(Connect(View))                                                                                                                                                                           
    at Route (/opt/sandbox/clean-volto-project/node_modules/react-router/cjs/react-router.js:470:29)                                                                                                       
    at Switch (/opt/sandbox/clean-volto-project/node_modules/react-router/cjs/react-router.js:676:29)                                                                                                      
    at main
```

**Pull request merged**
